# SOPS Configuration File
# Static configuration with pre-generated random key ID

creation_rules:
  - path_regex: '.*'
    pgp: 'F09CDCB0DBC34F6F'

# GPG key groups
key_groups:
  - pgp:
      - 'F09CDCB0DBC34F6F'